[package]
authors = ["alex <acdenissk69@gmail.com>", "Zeyla Hellyer <zey@zey.moe>"]
description = "A Rust library for the Discord API."
documentation = "https://docs.rs/serenity"
homepage = "https://github.com/serenity-rs/serenity"
keywords = ["discord", "api"]
license = "ISC"
name = "serenity"
readme = "README.md"
repository = "https://github.com/serenity-rs/serenity.git"
version = "0.6.0"

[dependencies]
bitflags = "^1.0"
futures = "~0.1"
log = "~0.4"
serde = "^1.0"
serde_derive = "^1.0"
serde_json = "^1.0"
tokio = "~0.1"
tokio-tls = "~0.1"
url = "^1.0"

[dependencies.base64]
optional = true
version = "~0.9"

[dependencies.byteorder]
optional = true
version = "^1.0"

[dependencies.chrono]
features = ["serde"]
version = "~0.4"

[dependencies.flate2]
optional = true
version = "^1.0"

[dependencies.http]
optional = true
version = "~0.1"

[dependencies.hyper]
optional = true
version = "~0.12"

[dependencies.hyper-tls]
optional = true
version = "~0.3"

[dependencies.opus]
optional = true
version = "0.2"

[dependencies.rand]
optional = true
version = "^0.5"

[dependencies.sodiumoxide]
default-features = false
optional = true
version = "0.0.14"

[dependencies.tokio-tungstenite]
git = "https://github.com/snapview/tokio-tungstenite"
optional = true

[dev-dependencies.matches]
version = "0.1.6"

[features]
default = [
    "builder",
    "client",
    "gateway",
    "http-client",
    "utils",
]
builder = ["utils"]
client = ["gateway", "http"]
extras = []
framework = ["client", "utils"]
gateway = ["flate2", "http", "tokio-tungstenite", "utils"]
http-client = ["builder", "hyper", "hyper-tls", "utils"]
standard_framework = ["framework"]
utils = ["base64"]
voice = ["byteorder", "gateway", "opus", "rand", "sodiumoxide"]

[package.metadata.docs.rs]
all-features = true

[patch.crates-io]
tokio-tls = { git = "https://github.com/aep/tokio-tls.git", rev = "7865734d2167160cabd4422aca76b8478e643b41" }
